title: John Pauline Pineda # your name (or website title) here
logo: "/images/JohnPaulinePineda.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Part Engineer,
  <br>
  Part Statistician,
  <br>
  100% Lifelong Learner.
  <br><br>
  <a href="https://www.linkedin.com/in/johnpaulinepineda/">LinkedIn</a> 
  <br>
  <a href="https://www.researchgate.net/profile/John-Pauline-Pineda">ResearchGate</a> 
  <br>
  <a href="https://github.com/JohnPaulinePineda">GitHub</a> 
  <br>
  <a href="https://public.tableau.com/app/profile/john.pauline.pineda">Tableau Public</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
