title: John Pauline Pineda # your name (or website title) here
logo: "/images/JPP_MasterOfStatistics.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Part Engineer,
  <br><br>
  Part Statistician,
  <br><br>
  100% Lifelong Learner.
  <br><br>
  <a href="https://www.linkedin.cn/incareer/in/ACoAAAHVJJ8BLIVIDosazFX1GAfzRjfmQf8FfsY">LinkedIn/InCareer</a> 
  <br><br>
  <a href="https://www.researchgate.net/profile/John-Pauline-Pineda">ResearchGate</a> 
  <br><br>
  <a href="https://rpubs.com/JoPaPi">RPubs</a> 
  <br><br>
  <a href="https://twitter.com/yuehanbaolin">Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
